name: Main
on:
  workflow_dispatch:
  repository_dispatch:
  push:
    branches:
      - '**'
      - '!feature'
      - '!feature'
    tags:
      - '**'
    paths-ignore:
      - '**.md'
      - 'tools/**'
      - '.github/patches/duckdb-wasm/**'
      - '.github/workflows/**'
      - '!.github/workflows/Main.yml'
      - '.github/config/uncovered_files.csv'
  pull_request:
    types: [opened, reopened, ready_for_review]
    paths-ignore:
      - '**.md'
      - 'tools/**'
      - '.github/patches/duckdb-wasm/**'
      - '.github/workflows/**'
      - '!.github/workflows/Main.yml'
      - '.github/config/uncovered_files.csv'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.head_ref || '' }}-${{ github.base_ref || '' }}-${{ github.ref != 'refs/heads/feature' || github.sha }}
  cancel-in-progress: true

env:
  GH_TOKEN: ${{ secrets.GH_TOKEN }}

jobs:
 linux-debug:
    name: Linux Debug
    runs-on: ubuntu-20.04

    env:
      CC: gcc-10
      CXX: g++-10
      TREAT_WARNINGS_AS_ERRORS: 1
      BUILD_VISUALIZER: 1
      BUILD_INET: 1
      BUILD_TPCH: 1
      BUILD_TPCDS: 1
      BUILD_FTS: 1
      BUILD_ICU: 1
      BUILD_JSON: 1
      BUILD_EXCEL: 1
      BUILD_PARQUET: 1
      BUILD_JEMALLOC: 1
      GEN: ninja

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Install
      shell: bash
      run: sudo apt-get update -y -qq && sudo apt-get install -y -qq ninja-build

    - name: Setup Ccache
      uses: hendrikmuhs/ccache-action@main
      with:
        key: ${{ github.job }}
        save: ${{ github.ref == 'refs/heads/feature' || github.repository != 'inacionery/duckdb' }}

    - name: Build
      shell: bash
      run:  make debug


 force-storage:
    name: Force Storage
    runs-on: ubuntu-20.04
    needs: linux-debug
    env:
      CC: gcc-10
      CXX: g++-10
      GEN: ninja
      BUILD_ICU: 1
      BUILD_INET: 1
      BUILD_PARQUET: 1
      BUILD_TPCH: 1
      BUILD_TPCDS: 1
      BUILD_FTS: 1
      BUILD_VISUALIZER: 1
      BUILD_JSON: 1
      BUILD_EXCEL: 1
      BUILD_JEMALLOC: 1

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Install
      shell: bash
      run: sudo apt-get update -y -qq && sudo apt-get install -y -qq ninja-build

    - name: Setup Ccache
      uses: hendrikmuhs/ccache-action@main
      with:
        key: ${{ github.job }}
        save: ${{ github.ref == 'refs/heads/feature' || github.repository != 'inacionery/duckdb' }}

    - name: Build
      shell: bash
      run: make reldebug

 force-restart:
    name: Force Restart
    runs-on: ubuntu-20.04
    needs: linux-debug
    env:
      CC: gcc-10
      CXX: g++-10
      GEN: ninja
      BUILD_ICU: 1
      BUILD_INET: 1
      BUILD_PARQUET: 1
      BUILD_TPCH: 1
      BUILD_TPCDS: 1
      BUILD_FTS: 1
      BUILD_VISUALIZER: 1
      BUILD_JSON: 1
      BUILD_EXCEL: 1
      BUILD_JEMALLOC: 1

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Install
      shell: bash
      run: sudo apt-get update -y -qq && sudo apt-get install -y -qq ninja-build

    - name: Setup Ccache
      uses: hendrikmuhs/ccache-action@main
      with:
        key: ${{ github.job }}
        save: ${{ github.ref == 'refs/heads/feature' || github.repository != 'inacionery/duckdb' }}

    - name: Build
      shell: bash
      run: make reldebug

 valgrind:
    name: Valgrind
    runs-on: ubuntu-20.04
    needs: linux-debug
    env:
      CC: gcc-10
      CXX: g++-10
      DISABLE_SANITIZER: 1
      BUILD_JEMALLOC: 1
      GEN: ninja

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Install
      shell: bash
      run: sudo apt-get update -y -qq && sudo apt-get install -y -qq ninja-build valgrind

    - name: Setup Ccache
      uses: hendrikmuhs/ccache-action@main
      with:
        key: ${{ github.job }}
        save: ${{ github.ref == 'refs/heads/feature' || github.repository != 'inacionery/duckdb' }}

    - name: Build
      shell: bash
      run: make debug

 docs:
    name: Website Docs
    runs-on: ubuntu-20.04
    needs: linux-debug
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Clone Website
      shell: bash
      run: git clone https://github.com/inacionery/duckdb-web

    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Package
      shell: bash
      run: |
        cd duckdb-web
        python3 scripts/generate_docs.py ..

 odbc:
    name: ODBC
    runs-on: ubuntu-22.04
    needs: linux-debug
    env:
      BUILD_ODBC: 1
      GEN: ninja

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - uses: actions/setup-python@v4
      with:
        python-version: '3.7'

    - name: Dependencies
      shell: bash
      run: |
        sudo apt-get update -y -qq
        sudo apt-get install -y -qq ninja-build unixodbc-dev
        pip3 install pyodbc

    - name: Install nanodbc
      shell: bash
      run: |
        wget https://github.com/nanodbc/nanodbc/archive/refs/tags/v2.14.0.tar.gz -O nanodbc.tgz
        mkdir nanodbc
        tar xvf nanodbc.tgz -C nanodbc --strip-components=1
        cd nanodbc
        wget https://github.com/catchorg/Catch2/releases/download/v2.13.9/catch.hpp
        cp catch.hpp test/catch/catch.hpp
        sed -i -e "s/set(test_list/set(test_list odbc/" test/CMakeLists.txt
        mkdir build
        cd build
        cmake -DNANODBC_DISABLE_TESTS=OFF ..
        cmake --build .

    - name: Install psqlodbc
      shell: bash
      run: |
        git clone https://github.com/Mytherin/psqlodbc.git
        (cd psqlodbc && git checkout edd9890a5046a2006f210849abb97c6a6589a45c && make debug)

    - name: Setup Ccache
      uses: hendrikmuhs/ccache-action@main
      with:
        key: ${{ github.job }}
        save: ${{ github.ref == 'refs/heads/feature' || github.repository != 'inacionery/duckdb' }}

    - name: Build
      shell: bash
      run: DISABLE_SANITIZER=1 make debug
